apiVersion: apps/v1
kind: Deployment
metadata:
  name: stb
  namespace: toqqer-stb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stb
  template:
    metadata:
      labels:
        app: stb
    spec:
      serviceAccountName: default
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: toqqer-qc-pvc
      containers:
        - name: stb
          image: toqqer/toqqer:stb_ov1
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "--"]
          args: ["java -jar stb-0.0.1-SNAPSHOT.jar"]
          ports:
            - containerPort: 8020
          volumeMounts:
            - name: persistent-storage
              mountPath: "/data_2"
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              cpu: 1200m
              memory: 4000Mi
          readinessProbe:
            tcpSocket:
              port: 8020
            initialDelaySeconds: 120
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 8020
            initialDelaySeconds: 120
            periodSeconds: 20
