apiVersion: v1
kind: PersistentVolume
metadata:
  name: toqqer-qc-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"
  persistentVolumeReclaimPolicy: Retain
