apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toqqer-qc-pvc
  namespace: toqqer-qc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: toqqer-qc-pv
