apiVersion: v1
kind: Service
metadata:
  name: stb-service
  namespace: toqqer-stb
spec:
  type: NodePort
  selector:
    app: stb
  ports:
    - port: 8020
      targetPort: 8020
      nodePort: 30080
